package me.geso.hana.abstractrow;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Blob;
import java.util.List;
import java.util.Arrays;
import java.util.stream.Stream;
import java.util.Optional;
import java.time.Instant;
import javax.annotation.Generated;

import me.geso.hana.annotation.Table;
import me.geso.hana.Insert;
import me.geso.hana.Criteria;
import me.geso.hana.HanaException;
import me.geso.hana.Select;

@Generated(value={}, comments="Generated by me.geso.hana.generator.RowClassGenerator")
@SuppressWarnings("unused")
@Table(name = "member")
public abstract class AbstractMember extends me.geso.hana.AbstractRow {
	public String getTableName() { return "member"; }
	private static final List<String> primaryKeys = Arrays.asList("id");
	@Override
	public List<String> getPrimaryKeys() {
		return primaryKeys;
	}

	@Override
	public void initialize(ResultSet rs) throws SQLException {
		ResultSetMetaData meta = rs.getMetaData();
		int columnCount = meta.getColumnCount();
		for (int i=1; i<columnCount+1; ++i) {
			String label = meta.getColumnLabel(i);
			switch (label) {
			case "id":
				this.id = rs.getLong(i);
				this._HaNa_selected_id = true;
				break;
			case "email":
				this.email = rs.getString(i);
				this._HaNa_selected_email = true;
				break;
			case "created_on":
				this.created_on = rs.getLong(i);
				this._HaNa_selected_created_on = true;
				break;
			case "updated_on":
				this.updated_on = rs.getLong(i);
				this._HaNa_selected_updated_on = true;
				break;
			} // switch
		} // for
	}
	public me.geso.hana.row.Member insert(Connection connection) throws SQLException, HanaException {
		Insert insert = Insert.into(this.getTableName());
		if (_HaNa_dirty_id) {
			insert.value("id", this.getId());
		}
		if (_HaNa_dirty_email) {
			insert.value("email", this.getEmail());
		}
		if (_HaNa_dirty_created_on) {
			insert.value("created_on", this.getCreatedOn());
		}
		if (_HaNa_dirty_updated_on) {
			insert.value("updated_on", this.getUpdatedOn());
		}
		PreparedStatement stmt = insert.build(connection).prepare(connection);
		stmt.execute();
		try (ResultSet rs = stmt.getGeneratedKeys();) {
			if (rs.next()) {
				this.setId(rs.getLong(1));
				this._HaNa_selected_id = true;
			}
		}
		return (me.geso.hana.row.Member)this;
	}

	public static Optional<me.geso.hana.row.Member> find(Connection connection, long id) throws SQLException, HanaException {
		return Select.from(me.geso.hana.row.Member.class)
		.where(me.geso.hana.Condition.eq("id", id))
		.stream(connection).findFirst();
	}

	public Optional<me.geso.hana.row.Member> refetch(Connection connection) throws SQLException, HanaException {
		return AbstractMember.find(connection,id);
	}

	public static long count(Connection connection) throws SQLException, HanaException {
		return Select.from(AbstractMember.class).count(connection)
;	}
	@Override
	public Criteria criteria() throws SQLException, HanaException {
		if (!this._HaNa_selected_id) {
				throw new HanaException("The row doesn't contain *selected* primary key: id");
		}

		Criteria criteria = null;
		criteria = me.geso.hana.Condition.and(criteria, me.geso.hana.Condition.eq("id", this.getId()));
		return criteria;
	}
	@Override
	protected void setUpdateParameters(me.geso.hana.Update update) throws HanaException, SQLException {
		if (_HaNa_dirty_id) {
			update.set("id", this.getId());
		}
		if (_HaNa_dirty_email) {
			update.set("email", this.getEmail());
		}
		if (_HaNa_dirty_created_on) {
			update.set("created_on", this.getCreatedOn());
		}
		if (_HaNa_dirty_updated_on) {
			update.set("updated_on", this.getUpdatedOn());
		}
	}
       @Override
	public String toString() {
		return "AbstractMember ["
			+ " id=" + id
			+ " email=" + email
			+ " created_on=" + created_on
			+ " updated_on=" + updated_on
		+ "]";
	}
	// Column: id BIGINT(19)
	private long id;

	private boolean _HaNa_dirty_id;	private boolean _HaNa_selected_id;	public long getId() {
		return this.id;
	}

	public me.geso.hana.row.Member setId(long value) {
		this.id = value;
		_HaNa_dirty_id = true;
		return (me.geso.hana.row.Member)this;
	}

	// Column: email VARCHAR(255)
	private String email;

	private boolean _HaNa_dirty_email;	private boolean _HaNa_selected_email;	public String getEmail() {
		return this.email;
	}

	public me.geso.hana.row.Member setEmail(String value) {
		this.email = value;
		_HaNa_dirty_email = true;
		return (me.geso.hana.row.Member)this;
	}

	// Column: created_on INTEGER(10)
	private long created_on=Instant.now().getEpochSecond();

	private boolean _HaNa_dirty_created_on;	private boolean _HaNa_selected_created_on;	public long getCreatedOn() {
		return this.created_on;
	}

	public me.geso.hana.row.Member setCreatedOn(long value) {
		this.created_on = value;
		_HaNa_dirty_created_on = true;
		return (me.geso.hana.row.Member)this;
	}

	// Column: updated_on INTEGER(10)
	private long updated_on;

	private boolean _HaNa_dirty_updated_on;	private boolean _HaNa_selected_updated_on;	public long getUpdatedOn() {
		return this.updated_on;
	}

	public me.geso.hana.row.Member setUpdatedOn(long value) {
		this.updated_on = value;
		_HaNa_dirty_updated_on = true;
		return (me.geso.hana.row.Member)this;
	}

}
